# Generated by Django 6.0.7 on 2026-07-22 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrecord',
            name='assigned_inspector',
            field=models.ForeignKey(blank=True, db_column='assigned_inspector_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_facilities', to='api.user'),
        ),
    ]
