# Generated by Django 6.0.7 on 2026-07-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clientrecord_assigned_inspector'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggproductionverification',
            name='powder_sold_to_trade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
