# Generated by Django 6.0.7 on 2026-07-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_eggproductionverification_powder_sold_to_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrecord',
            name='approval_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eggproductionverification',
            name='egg_purchase_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='eggproductionverification',
            name='eggs_produced_during_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='eggproductionverification',
            name='exported',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='eggproductionverification',
            name='powder_conversion_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='eggproductionverification',
            name='powder_converted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='eggproductionverification',
            name='powder_opening_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='eggproductionverification',
            name='powder_purchase_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='eggproductionverification',
            name='powder_purchased',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='eggproductionverification',
            name='powder_sold_to_producers',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='eggproductionverification',
            name='pulp_conversion_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='eggproductionverification',
            name='pulp_purchase_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='eggproductionverification',
            name='transfer_purchase_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='eggproductionverification',
            name='transferred_or_purchased_from_producers',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
